GameMessage::SetStunned(
	SetStunned {
		originator: 0,
		state_change_type: StunState::Push,
		cant_attack: true,
		cant_attack_out_change_was_applied: false,
		cant_equip: false,
		cant_equip_out_change_was_applied: false,
		cant_interact: false,
		cant_interact_out_change_was_applied: false,
		cant_jump: false,
		cant_jump_out_change_was_applied: false,
		cant_move: true,
		cant_move_out_change_was_applied: false,
		cant_turn: true,
		cant_turn_out_change_was_applied: false,
		cant_use_item: false,
		cant_use_item_out_change_was_applied: false,
		dont_terminate_interact: false,
		ignore_immunity: true,
	},
)
