CharacterConstruction {
	claim_code_1: Some(1),
	claim_code_2: Some(2),
	claim_code_3: Some(3),
	claim_code_4: Some(4),
	hair_color: 5,
	hair_style: 6,
	torso_color: 7,
	legs_color: 8,
	torso_decal: 9,
	eyebrows_style: 10,
	eyes_style: 11,
	mouth_style: 12,
	account_id: 13,
	last_logout: 14,
	prop_mod_last_display_time: 15,
	u_score: 16,
	is_free_trial: true,
	total_currency_collected: 17,
	total_bricks_collected: 18,
	total_smashables_smashed: 19,
	total_quickbuilds_completed: 20,
	total_enemies_smashed: 21,
	total_rockets_used: 22,
	total_missions_completed: 23,
	total_pets_tamed: 24,
	total_imagination_powerups_collected: 25,
	total_life_powerups_collected: 26,
	total_armor_powerups_collected: 27,
	total_distance_traveled: 28,
	times_smashed_count: 29,
	total_damage_taken: 30,
	total_damage_healed: 31,
	total_armor_repaired: 32,
	total_imagination_restored: 33,
	total_imagination_used: 34,
	total_distance_driven: 35,
	total_time_airborne_in_a_race_car: 36,
	total_racing_imagination_powerups_collected: 37,
	total_racing_imagination_crates_smashed: 38,
	total_racing_car_boosts_activated: 39,
	total_racing_wrecks: 40,
	total_racing_smashables_smashed: 41,
	total_races_finished: 42,
	total_first_place_race_finishes: 43,
	transition_state: TransitionState::Arrive {
		last_custom_build_parts: lu!("1;2;3")
	},
	gm_pvp_info: Some(GmPvpInfo {
		pvp_enabled: true,
		is_gm: true,
		gm_level: 44,
		editor_enabled: true,
		editor_level: 45,
	}),
	current_activity: Some(GameActivity::Quickbuilding),
	social_info: Some(SocialInfo {
		guild_id: 46,
		guild_name: lu!("guild"),
		is_lego_club_member: true,
	}),
}
