DestroyableConstruction {
	status_immunity_info: Some(StatusImmunityInfo {
		immune_to_basic_attack: 0,
		immune_to_damage_over_time: 1,
		immune_to_knockback: 2,
		immune_to_interrupt: 3,
		immune_to_speed: 4,
		immune_to_imagination_gain: 5,
		immune_to_imagination_loss: 6,
		immune_to_quickbuild_interrupt: 7,
		immune_to_pull_to_point: 8,
	}),
	stats_info: Some(StatsInfo {
		cur_health: 9,
		max_health: 10.0,
		cur_armor: 11,
		max_armor: 12.0,
		cur_imag: 13,
		max_imag: 14.0,
		damage_absorption_points: 15,
		immunity: true,
		is_gm_immune: true,
		is_shielded: true,
		actual_max_health: 16.0,
		actual_max_armor: 17.0,
		actual_max_imag: 18.0,
		factions: vec![19].into(),
		is_dead: true,
		is_smashed: true,
		smashable_info: Some(SmashableInfo {
			is_module_assembly: true,
			explode_factor: Some(20.0),
		}),
	}),
	is_on_a_threat_list: Some(true),
}
